theme: minima
title: Talia Armato-Helle
author: italianhelle
email: italianhelle@github.com
description: > # this means to ignore newlines until "baseurl:"
  This site will be related to all things Hulk and Hocus Pocus :jack-o-lantern
# social links
twitter_username: 
github_username:  italianhelle

show_excerpts: true # set to false to remove excerpts on the homepage
